import {
  SiReact,
  SiLaravel,
  SiPhp,
  SiTailwindcss,
  SiNextdotjs,
  SiDocker,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiGithub,
  SiGo,
  SiNodedotjs,
  SiJavascript,
  SiBootstrap,
  SiPython,
  SiNginx,
} from "react-icons/si"

export const techIcons = {
  react: SiReact,
  laravel: SiLaravel,
  php: SiPhp,
  tailwind: SiTailwindcss,
  nextjs: SiNextdotjs,
  docker: SiDocker,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  github: SiGithub,
  golang: SiGo,
  node: SiNodedotjs,
  javascript: SiJavascript,
  bootstrap: SiBootstrap,
  python: SiPython,
  nginx: SiNginx,
}